theme: jekyll-theme-slate
plugins:
  - jekyll-relative-links
  - jekyll-include-absolute
relative_links:
  enabled: true
  collections: true
title: JS1 Help
description: How-To's from Mr. Hinkle's Intro to JavaScript Class
