theme: jekyll-theme-slate
markdown: kramdown
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
title: Web Design Instructions
description: How-To's from Mr. Hinkle's Intro to Web Design Class
